### ISSUE TITLE
Suggestion: show (and compare) checksum

### ISSUE THREAD

**Issue by Morganlej** [papoteur-mga/isodumper#26]
-Yes it is easy to perfome manually, but so is flash writing - i think it wold be a logical and convenient feature.
Checksumming is usually a good idea to perform.
I suggest to add buttons to calculate and show md5 and sha256 checksums
Added twist: have a field "paste a checksum here" where a checksum can be pasted and then length of it trig checking of the correct checksums calculation, compare to the pasted sum, and show red or green light !
For the checksum given fron the download site.

**Comment by papoteur-mga** [comment]
I added a computing step at the end of the writing step, to calculate and display the SHA1 and MD5 sums. The direct check is lot of complication for a little gain. I don't plan to add it.
In 0.40 release.
The checksum for a USB device is funded on the ISO source size.
